#!/usr/bin/env bash
# Sync knockout predictions from the local SQLite DB → src/data/knockoutPredictions.ts
# so changes made via `npm run dev` are reflected on the live GitHub Pages site.
#
# Usage:  ./sync-knockout.sh [--commit]
#
#   --commit  Also git add, commit, and push the change.

set -euo pipefail
cd "$(dirname "$0")"

DB_PATH="server/db/data/scoreboard.db"
OUT_PATH="src/data/knockoutPredictions.ts"

if [ ! -f "$DB_PATH" ]; then
  echo "❌ Database not found at $DB_PATH — run 'npm run dev' first."
  exit 1
fi

node -e "
const Database = require('better-sqlite3');
const db = new Database('$DB_PATH');

const rows = db.prepare(\`
  SELECT kp.participant_id, p.name, kp.r32_picks_json, kp.qf_picks_json,
         kp.sf_picks_json, kp.final_picks_json, kp.champion_pick, kp.updated_at
  FROM knockout_predictions kp
  JOIN participants p ON p.id = kp.participant_id
  ORDER BY p.name
\`).all();

if (rows.length === 0) {
  console.log('ℹ️  No knockout predictions in DB yet — writing empty file.');
}

const predictions = rows.map(r => ({
  participantId: r.participant_id,
  participantName: r.name,
  r32Picks: JSON.parse(r.r32_picks_json),
  qfPicks: JSON.parse(r.qf_picks_json),
  sfPicks: JSON.parse(r.sf_picks_json),
  finalPicks: JSON.parse(r.final_picks_json),
  championPick: r.champion_pick,
  updatedAt: r.updated_at,
}));

function q(s) { return JSON.stringify(s); }
function arr(a) { return '[' + a.map(q).join(', ') + ']'; }

let out = \"import type { KnockoutPrediction } from '../types';\\n\\n\";
out += '/**\\n * All participants\\' knockout predictions.\\n';
out += ' * Auto-generated by sync-knockout.sh — do not edit by hand.\\n */\\n';
out += 'export const KNOCKOUT_PREDICTIONS: KnockoutPrediction[] = [\\n';
for (const p of predictions) {
  out += '  {\\n';
  out += '    participantId: ' + q(p.participantId) + ',\\n';
  out += '    participantName: ' + q(p.participantName) + ',\\n';
  out += '    r32Picks: ' + arr(p.r32Picks) + ',\\n';
  out += '    qfPicks: ' + arr(p.qfPicks) + ',\\n';
  out += '    sfPicks: ' + arr(p.sfPicks) + ',\\n';
  out += '    finalPicks: ' + arr(p.finalPicks) + ',\\n';
  out += '    championPick: ' + q(p.championPick) + ',\\n';
  out += '    updatedAt: ' + q(p.updatedAt) + ',\\n';
  out += '  },\\n';
}
out += '];\\n';

require('fs').writeFileSync('$OUT_PATH', out);
console.log('✅ Synced ' + predictions.length + ' knockout predictions → $OUT_PATH');
"

if [ "${1:-}" = "--commit" ]; then
  git add "$OUT_PATH"
  if git diff --cached --quiet; then
    echo "ℹ️  No changes to commit."
  else
    git commit -m "Sync knockout predictions from DB

Co-Authored-By: Claude <noreply@anthropic.com>"
    git push
    echo "🚀 Pushed! GitHub Pages will redeploy shortly."
  fi
fi
