#!/usr/bin/env bash
# Sync participants from the local SQLite DB into src/data/participants.ts
# so changes made via `npm run dev` are reflected on the live GitHub Pages site.
#
# Usage:  ./sync-participants.sh [--commit]
#
#   --commit  Also git add, commit, and push the change.

set -euo pipefail
cd "$(dirname "$0")"

DB_PATH="server/db/data/scoreboard.db"
OUT_PATH="src/data/participants.ts"

if [ ! -f "$DB_PATH" ]; then
  echo "❌ Database not found at $DB_PATH — run 'npm run dev' first."
  exit 1
fi

node -e "
const Database = require('better-sqlite3');
const db = new Database('$DB_PATH');
const rows = db.prepare('SELECT id, name, predictions_json FROM participants ORDER BY id').all();
const ps = rows.map(r => ({ id: r.id, name: r.name, predictions: JSON.parse(r.predictions_json) }));
let out = \"import { Participant } from '../types';\\n\\n/**\\n * All \" + ps.length + \" participants' predictions.\\n * Auto-generated by sync-participants.sh — do not edit by hand.\\n */\\nexport const INITIAL_PARTICIPANTS: Participant[] = [\\n\";
for (const p of ps) {
  out += '  {\\n';
  out += \"    id: '\"+p.id+\"',\\n    name: '\"+p.name+\"',\\n    predictions: [\\n\";
  for (const pr of p.predictions) out += \"      { groupName: '\"+pr.groupName+\"', champion: '\"+pr.champion+\"', runnerUp: '\"+pr.runnerUp+\"' },\\n\";
  out += '    ],\\n  },\\n';
}
out += '];\\n';
require('fs').writeFileSync('$OUT_PATH', out);
console.log('✅ Synced ' + ps.length + ' participants → $OUT_PATH');
"

if [ "${1:-}" = "--commit" ]; then
  git add "$OUT_PATH"
  if git diff --cached --quiet; then
    echo "ℹ️  No changes to commit."
  else
    git commit -m "Sync participants from DB

Co-Authored-By: Claude <noreply@anthropic.com>"
    git push
    echo "🚀 Pushed! GitHub Pages will redeploy shortly."
  fi
fi
