import type { KnockoutPrediction } from '../types';

/**
 * All participants' knockout predictions.
 * Auto-generated by sync-knockout.sh — do not edit by hand.
 */
export const KNOCKOUT_PREDICTIONS: KnockoutPrediction[] = [
  {
    participantId: "p_litielong",
    participantName: "李铁龙",
    r32Picks: ["Canada", "Germany", "Morocco", "Brazil", "France", "Norway", "Mexico", "England", "United States", "Belgium", "Portugal", "Spain", "Switzerland", "Argentina", "Colombia", "Egypt"],
    qfPicks: ["France", "Morocco", "Brazil", "England", "Spain", "Belgium", "Argentina", "Colombia"],
    sfPicks: ["France", "Spain", "Brazil", "Argentina"],
    finalPicks: ["France", "Argentina"],
    championPick: "France",
    updatedAt: "2026-06-29T15:36:18.962Z",
  },
];
